services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "4000:4000"
    environment:
      - DATABASE_URL=ecto://postgres:postgres@db/speech2text_dev
      - SECRET_KEY_BASE=$PHX_SECRET_KEY_BASE
      - PHX_HOST=localhost
      - PORT=4000
      - PGUSER=postgres
      - PGPASSWORD=postgres
      - PGHOST=db
      - PGPORT=5432
      - PGDATABASE=speech2text_dev
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: postgres:17.2
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=speech2text_prod
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: