ARG DEBIAN_VERSION=bullseye-20241223-slim

FROM debian:${DEBIAN_VERSION}

RUN apt-get update && apt-get install -y \
    apt-transport-https \
    ca-certificates \
    gnupg \
    curl

RUN echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | \
    tee -a /etc/apt/sources.list.d/google-cloud-sdk.list && \
    curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | \
    gpg --dearmor -o /usr/share/keyrings/cloud.google.gpg

# Install the Google Cloud SDK
# We do this in a separate RUN command to keep layers logically separated
RUN apt-get update && apt-get install -y \
    google-cloud-cli \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Download and install Cloud SQL proxy directly
RUN curl -o /usr/local/bin/cloud-sql-proxy \
    https://storage.googleapis.com/cloud-sql-connectors/cloud-sql-proxy/v2.8.1/cloud-sql-proxy.linux.amd64 && \
    chmod +x /usr/local/bin/cloud-sql-proxy

WORKDIR /cli

COPY . .